# Generated by Django 4.2 on 2023-08-12 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=256)),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('round_num', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.tournaments')),
            ],
            options={
                'db_table': 'rounds',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=uuid.UUID('ce6ee463-a1c9-4a77-a7c5-15496b60b72a'), max_length=256)),
                ('score', models.IntegerField()),
                ('checked_in', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.tournaments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Pairings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_p1', models.IntegerField(default=0)),
                ('result_p2', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('checked_in', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.rounds')),
            ],
            options={
                'db_table': 'pairings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_admins',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.tournaments'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField()),
                ('warning_type', models.CharField()),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.tournaments')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
