# Generated by Django 4.2 on 2023-08-12 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.CharField(default=uuid.UUID('a188484f-f0e8-49e0-994a-2702fc58389d'), max_length=256),
        ),
    ]
