# Generated by Django 4.2 on 2023-08-12 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0002_alter_participants_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.CharField(default=uuid.UUID('518c2212-4072-4d40-bf05-09bde556d80a'), max_length=256),
        ),
    ]
