# Generated by Django 4.2 on 2023-08-12 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0003_alter_participants_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.CharField(default=uuid.UUID('37e2153c-d319-4fba-864a-c7b012d13fe2'), max_length=256),
        ),
    ]
